name: Publicar no Dev.to

on:
  push:
    branches:
      - main
    # paths:
    #   - "_posts/*.md"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extrair conteúdo do post
        id: extract_post
        run: |
          git fetch --all
          FILE=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '^_posts/.*\.md' | head -n 1)
          if [ -z "$FILE" ]; then
            echo "Nenhum novo post encontrado."
            exit 0
          fi
          echo "FILE=$FILE" >> $GITHUB_ENV

      - name: Publicar no Dev.to
        if: env.FILE != ''
        env: 
          TOKEN_DEVTO: ${{ secrets.DEVTO_API_KEY }}
        run: |
          CONTENT=$(cat ${{ env.FILE }})
          JSON_DATA=$(jq -n --arg body "$CONTENT" '{ article: { title: "Meu Artigo", body_markdown: $body, published: true }}')
          curl -X POST "https://dev.to/api/articles" \
            -H "Content-Type: application/json" \
            -H "api-key: $TOKEN_DEVTO" \
            -d "$JSON_DATA"
